### ISSUE TITLE
new RabbitWorkQueue error

### ISSUE THREAD

**Issue by dockerliu** [khalidsalomao/SimpleHelpers.Net.RabbitMQ#2]
Hi,bro,
I use Example 1 try to Publishing messages,
But encountered the following error:
![image](https://user-images.githubusercontent.com/57223447/115427934-cd67e980-a1f9-11eb-8ce1-31dc165bf792.png)

**Comment by khalidsalomao** [comment]
Hi @dockerliu !

Thanks for the report! 

About the exception, it is handled by the `try... catch` block. So it will work without any problem.
The IDE stopped at the exception because it is probably running in DEBUG mode and configured to stop at any exception. Your code should run without problem if you adjust your debugger settings or run outside your IDE or run this in production.

About the code quality ;) , yes indeed this exception can (and should) be avoided with a small refactoring of the `GetConnection` code! 
Thank you very much for noticing that. I will adjust the code to avoid throwing avoidable exceptions.

Best,
Khalid

**Comment by dockerliu** [comment]
You are right, thank you for your reply.

Best,
Dockerliu
